name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: taiki-e/install-action@nextest
      - name: fmt
        run: cargo fmt --all --check
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: nextest
        run: cargo nextest run --no-fail-fast
      - name: doctests
        run: cargo test --doc
